# Exercise 1 
### A Amar Rohith 
### EC21B1106

## Question 1

In [1]:
import numpy as np

Array Creation and Basic Operation

a)Create a 1D array of numbers from 0 to 19 using np.arange(). 

In [2]:
Arr=np.arange(0,20)
print(Arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


b) Reshape this array into a 4x5 2D array.


In [3]:
'''np.reshape(Arr,(4,5))
print(Arr)'''

# or use the object to call the function

Arr=Arr.reshape((4,5))
print(Arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


 c) Create a 3x3 array of all zeros, and another 3x3 array of all ones. 


In [4]:
zeros=np.zeros((3,3))
ones=np.ones((3,3))
print(zeros,ones,sep='\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


d)Generate a 1D array of 10 evenly spaced numbers between 1 and 100 using np.linspace().


In [5]:
ans=np.linspace(1,100,10)
print(ans)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


 ii) Indexing, Slicing, and Iterating

In [6]:
#1 
print(Arr[2][3]) # or print(Arr[2,3])
#2
print(Arr[1][:]) # or print(Arr[1,:])
#3
print(Arr[:,-1])

13
[5 6 7 8 9]
[ 4  9 14 19]


 b) Reverse the order of elements in the second row.

In [7]:
print(f"prev arr={Arr}")
Arr[1,:]=Arr[1,:][::-1]
print(f"After arr={Arr}")

prev arr=[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
After arr=[[ 0  1  2  3  4]
 [ 9  8  7  6  5]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Create a 3x3 array with random integers between 1 and 100, then find
 all elements greater than 50.

In [8]:
random_matrix=np.random.randint(1,101,(3,3))
ele50=random_matrix[random_matrix>50]

print(random_matrix)
print(ele50)

[[38 85 41]
 [70 75  8]
 [18 24 20]]
[85 70 75]


iii) Conditional Statements and Boolean Operations a) Create a 5x5
 array of random integers between 0 and 100. b) Create a boolean mask
 for elements between 30 and 70 (inclusive). c) Use this mask to
 replace all elements outside this range with the value-1

In [9]:
random_matrix=np.random.randint(1,101,(5,5))
ele30to70=(random_matrix>=30)&(random_matrix<=70)
random_matrix[~ele30to70]=-1
print(random_matrix)
print(ele30to70)


[[69 -1 -1 -1 48]
 [-1 -1 70 -1 -1]
 [-1 63 -1 -1 32]
 [-1 -1 54 -1 -1]
 [-1 -1 -1 -1 66]]
[[ True False False False  True]
 [False False  True False False]
 [False  True False False  True]
 [False False  True False False]
 [False False False False  True]]


 iv) Basic Mathematical Operations


a) Create two 3x3 arrays with random integers between 1 and 10

In [10]:
mat1=np.random.randint(1,11,(3,3))
mat2=np.random.randint(1,11,(3,3))
print(f"mat1=\n{mat1} \n mat2=\n{mat2}")

mat1=
[[8 3 8]
 [7 7 6]
 [3 3 4]] 
 mat2=
[[ 2  5  6]
 [ 6 10  5]
 [ 1  2  6]]


 b) Perform element-wise addition, subtraction, multiplication, and
 division on these arrays

In [11]:

print(f"matadd=\n{mat1+mat2}")
print(f"matsub=\n{mat1-mat2}")
print(f"matmul=\n{mat1*mat2}")
print(f"matdiv=\n{mat1/mat2}")

matadd=
[[10  8 14]
 [13 17 11]
 [ 4  5 10]]
matsub=
[[ 6 -2  2]
 [ 1 -3  1]
 [ 2  1 -2]]
matmul=
[[16 15 48]
 [42 70 30]
 [ 3  6 24]]
matdiv=
[[4.         0.6        1.33333333]
 [1.16666667 0.7        1.2       ]
 [3.         1.5        0.66666667]]


 c) Calculate the dot product of these two arrays.

In [12]:
print(f"matdot=\n{mat1.dot(mat2)}")

matdot=
[[ 42  86 111]
 [ 62 117 113]
 [ 28  53  57]]


v) Universal Functions

a) Using the array from task 3a, calculate:
 ● The mean of the entire array.
 ● The standard deviation of each row.
 ● The variance of each column.
 ● The median of the entire array.
 ● The minimum and maximum values of each row.

In [13]:
random_matrix=np.random.randint(0,101,(5,5))
print(random_matrix)
print(f"mean={np.mean(random_matrix)}")
print(f"standard_deviation={np.std(random_matrix)}")
print(f"Variance of each_column={np.var(random_matrix,axis=0)}")
print(f"median={np.median(random_matrix)}")
print(f"min,max of each row={list(zip(random_matrix.min(axis=1),random_matrix.max(axis=1)))}")

[[ 44  69  42 100  39]
 [ 34  28  96  59   6]
 [ 43   1  81  33  52]
 [  0  10  71  64  89]
 [ 55  86  27  78  72]]
mean=51.16
standard_deviation=28.98369196634549
Variance of each_column=[ 354.16 1102.96  642.64  487.76  810.64]
median=52.0
min,max of each row=[(39, 100), (6, 96), (1, 81), (0, 89), (27, 86)]


  vi) Shape Manipulation

 a) Create a 1D array of 24 random integers between 0 and 100.

In [14]:
random_matrix=np.random.randint(0,101,(1,24))
print(random_matrix)

[[97 40 83 67 89 73 84 62 29 57 14 50 87  7 43 36  4 24 92 35 85 38  8 26]]


 b) Reshape this array into a 4x6 2D array.

In [15]:
random_matrix=random_matrix.reshape((4,6))
print(random_matrix)

[[97 40 83 67 89 73]
 [84 62 29 57 14 50]
 [87  7 43 36  4 24]
 [92 35 85 38  8 26]]


c) Flatten this 2D array back to 1D.

In [16]:
random_matrix=random_matrix.reshape((1,24))
print(random_matrix)
random_matrix=random_matrix.reshape((4,6))

[[97 40 83 67 89 73 84 62 29 57 14 50 87  7 43 36  4 24 92 35 85 38  8 26]]


In [17]:
Transpose=random_matrix.transpose()
print(Transpose)

[[97 84 87 92]
 [40 62  7 35]
 [83 29 43 85]
 [67 57 36 38]
 [89 14  4  8]
 [73 50 24 26]]


e) Stack two 3x3 arrays vertically, then stack the result with another 3x3
 array horizontally

In [18]:
M1=np.random.randint(0,11,(3,3))
M2=np.random.randint(0,11,(3,3))
M3=np.random.randint(0,11,(6,3))
print(M1,M2,M3,sep='\n')
res=np.vstack((M1,M2))
final_res=np.hstack((res,M3))

#print(np.concat)

print(final_res)

[[9 6 5]
 [3 1 0]
 [9 9 8]]
[[ 3  0  7]
 [ 9  7  2]
 [ 6 10  8]]
[[ 2 10  8]
 [ 1  8  6]
 [ 0  7  8]
 [ 8  6  8]
 [ 3  7  6]
 [ 5  4  2]]
[[ 9  6  5  2 10  8]
 [ 3  1  0  1  8  6]
 [ 9  9  8  0  7  8]
 [ 3  0  7  8  6  8]
 [ 9  7  2  3  7  6]
 [ 6 10  8  5  4  2]]


 vii) Copy Methods

 a) Create a 3x3 array of random integers
 b) Create three copies of this array using direct assignment, view(), and  copy().
  c) Modify an element in each copy and explain th 
 differences in how the original array is affected

In [19]:
M1=np.random.randint(0,11,(3,3))

M1_copy1=M1
M1_copy2=M1.view()
M1_copy3=M1.copy()

M1_copy1[0][0]=-1
M1_copy2[0][1]=-1
M1_copy3[0][2]=-1

print(f"original:\n{M1}\Copy1:\n{M1_copy1}\nCopy2:\n{M1_copy2}\nCopy3:\n{M1_copy3}")

original:
[[-1 -1 10]
 [ 1  0  4]
 [ 1  3  4]]\Copy1:
[[-1 -1 10]
 [ 1  0  4]
 [ 1  3  4]]
Copy2:
[[-1 -1 10]
 [ 1  0  4]
 [ 1  3  4]]
Copy3:
[[ 5 10 -1]
 [ 1  0  4]
 [ 1  3  4]]


Findings:

i)The "=" Assignment and the view does shallow copy
ii)The .copy attribute does deep copy.

 viii) Handling NULL Values

 a) Create a 4x4 array of random floats between 0 and 1.


In [20]:
M1=np.random.rand(4,4)
print(M1)

[[0.11358307 0.19905957 0.48670841 0.09932079]
 [0.5545784  0.71464815 0.8540987  0.58468514]
 [0.29918737 0.56859284 0.39308243 0.02578195]
 [0.38557271 0.94892353 0.50707776 0.04602762]]


b) Replace some values with NaN (Not a Number)

In [21]:
M1[0][1]=np.nan
M1[1][2]=np.nan
M1[2][3]=np.nan
M1[3][2]=np.nan

 c) Use np.isnan() to create a boolean mask identifying the NaN
 values

In [22]:
bool_mask=np.isnan(M1)
print(bool_mask)

[[False  True False False]
 [False False  True False]
 [False False False  True]
 [False False  True False]]


 d) Calculate the mean of the array, ignoring the NaN values.

In [23]:
print(np.mean(M1))

nan


 ix) Advanced Challenge

 a) Create a 10x10 array of random integers between 1 and 100.

In [24]:
Adv_Matrix=np.random.randint(1,101,(10,10))
print(Adv_Matrix)

[[ 73   2  85  73  10  16  17  63  12   3]
 [ 74  81  20  33  28  34  52  17  75  50]
 [ 64  86  27  24  87  28  54   2  40  17]
 [ 51  61  31  16  88  33  75  26  50  58]
 [ 63  63  14  52   3  84  63  76  35  93]
 [ 35   7  15  66  67  93  52  43   4 100]
 [ 13   8  85  37  90  30   4  79  26  51]
 [ 45  86  42  60  77  47  33  19  80  72]
 [ 98  66  21  32  99  41  78  32  48  27]
 [  4  43  94  69  75  82  75  96  10  69]]


In [25]:
Adv_Matrix=Adv_Matrix.flatten()
indices_flattend=np.argsort(Adv_Matrix)
indices_flattend=indices_flattend[-1:-6:-1]
indices_flattend=np.unravel_index(indices_flattend,(10,10))
index=list(zip(indices_flattend[0],indices_flattend[1]))
print(index)


[(5, 9), (8, 4), (8, 0), (9, 7), (9, 2)]


 c) Calculate the running average along each row (hint: look into
 np.cumsum())

In [26]:
Adv_Matrix=np.random.randint(1,101,(10,10))
div=np.arange(1,11)
cum_sum_matrix=np.cumsum(Adv_Matrix,axis=1)
res=cum_sum_matrix/div
print(f"Matrix=\n{Adv_Matrix}")
print(f"res=\n{res}")

Matrix=
[[10 10 21 49 26 17 69 57 49 13]
 [55 89 70 45 22 20  5 43 39 41]
 [83 81 25 21 42 51 10 50 70 54]
 [67 13 66 65 39 19 86 50 30 15]
 [96 44 98 50 92 71 27  2 78 36]
 [ 1 19 68 59 49 47 16 62 84 54]
 [74 40 69 48 33 16 86 12 68 31]
 [35 93 72 92  4 14 31 11 35 49]
 [64 75 50 22 19 76  3 32 69 59]
 [19  6 88 85 23 57 50 53 27  9]]
res=
[[10.         10.         13.66666667 22.5        23.2        22.16666667
  28.85714286 32.375      34.22222222 32.1       ]
 [55.         72.         71.33333333 64.75       56.2        50.16666667
  43.71428571 43.625      43.11111111 42.9       ]
 [83.         82.         63.         52.5        50.4        50.5
  44.71428571 45.375      48.11111111 48.7       ]
 [67.         40.         48.66666667 52.75       50.         44.83333333
  50.71428571 50.625      48.33333333 45.        ]
 [96.         70.         79.33333333 72.         76.         75.16666667
  68.28571429 60.         62.         59.4       ]
 [ 1.         10.         29.33333333 

d) Normalize each column of the array so that it sums to 1

In [27]:
Adv_Matrix=np.random.randint(1,101,(10,10))
div_col=np.sum(Adv_Matrix,axis=0)
Adv_Matrix=Adv_Matrix/div_col
print(f"Adv_Matrix:\n{Adv_Matrix}\n div_col:\n{div_col}")
print(np.sum(Adv_Matrix,axis=0))

Adv_Matrix:
[[0.04153355 0.08536585 0.08675799 0.01287554 0.02358491 0.08860759
  0.12317328 0.08389262 0.04145078 0.16122449]
 [0.07827476 0.14146341 0.07534247 0.01072961 0.03066038 0.10307414
  0.02296451 0.04362416 0.06217617 0.0122449 ]
 [0.11501597 0.18536585 0.00228311 0.04291845 0.17924528 0.15551537
  0.14822547 0.13758389 0.05699482 0.18367347]
 [0.09584665 0.15121951 0.07077626 0.05793991 0.14386792 0.03435805
  0.04384134 0.12751678 0.00259067 0.03469388]
 [0.07827476 0.01219512 0.0456621  0.16738197 0.04009434 0.01265823
  0.00417537 0.06711409 0.25647668 0.08979592]
 [0.13578275 0.11463415 0.14383562 0.20171674 0.00235849 0.15370705
  0.20250522 0.0704698  0.24870466 0.14897959]
 [0.13578275 0.06585366 0.09817352 0.03004292 0.10849057 0.01265823
  0.06471816 0.16778523 0.00777202 0.08571429]
 [0.04792332 0.00243902 0.15296804 0.18240343 0.22877358 0.16094033
  0.13778706 0.09899329 0.10621762 0.06734694]
 [0.14217252 0.22439024 0.11187215 0.10515021 0.17688679 0.11392405


## Question 2

 Write a python program to perform matrix operations on an M x N matrix and
 solve a system of linear equations. Use inbuilt functions to implement the
 operations. Get two matrices from the user. The program should support the
 following Menus,
 1. Matrix Addition
 2. Matrix Subtraction
 3. Scalar Matrix Multiplication
 4. Elementwise Matrix Multiplication
 5. Matrix Multiplication
 6. Matrix Transpose
 7. Trace of a Matrix
 8. Solve System of Linear Equations
 9. Determinant
 10. Inverse
 11. Eigen Value and Eigen Vector
 12. Exit


In [ ]:
#Note if you get an error make sure to pip insall tabulate

from IPython.display import clear_output
import numpy as np
from tabulate import *
import time
def setmatrix():
    M1=np.array(eval(input("Enter the Matrix1 as a list of list: ")))
    M2=np.array(eval(input("Enter the Matrix2 as a list of list: ")))
    return M1,M2




print("Waiting for  Matrix Initialization...")
M1,M2=setmatrix()

while True:
    
    print('''The choices are:\n
            1.Matrix Addition\n
            2.Matrix Subtraction\n
            3.Scalar Matrix Multiplication\n
            4.Elementwise Matrix Multiplication\n
            5.Matrix Multiplication\n
            6.Matrix Transpose\n
            7.Trace of a Matrix\n
            8.Solve System of Linear Equations\n
            9.Determinant\n
            10.Inverse\n
            11.Eigen Value and Eigen Vector\n
            12.reset Matrices\n
            13.exit\n''')
    
    choice=int(input("Enter the choice: "))
    if(choice==1):
        res=M1+M2
        print(tabulate(res,tablefmt='grid'))
        
    elif(choice==2):
        res=M1-M2
        print(tabulate(res,tablefmt='grid'))
        
    elif(choice==3):
        scalar=int(input("Enter the scalar to be multiplied with: "))
        matrix=int(input("Choose between matrix to multiply scalar with:\n 1-> matrix1\n 2->matrix2\n "))
        if matrix==1:
            matrix=M1
        else:
            matrix=M2                #default M2 is selected
        res=scalar*M2
        print(tabulate(res,tablefmt='grid'))
    elif(choice==4):
        res=M1*M2
        print(tabulate(res,tablefmt='grid'))
    elif(choice==5):
        res=M1.dot(M2)
        print(tabulate(res,tablefmt='grid'))
    elif(choice==6):
        matrix=int(input("Choose between matrix to Transpose :\n 1-> matrix1\n 2->matrix2\n "))
        if matrix==1:
            matrix=M1
        else:
            matrix=M2                #default M2 is selected
        res=matrix.T
        print(tabulate(res,tablefmt='grid'))
    elif(choice==7):
        matrix=int(input("Choose between matrix to find trace:\n 1-> matrix1\n 2->matrix2\n "))
        if matrix==1:
            matrix=M1
        else:
            matrix=M2                #default M2 is selected
        res=np.trace(matrix)
        print(res)
    elif(choice==8):
        print("Solves equation of the form Ax=B")
        A=eval(input("Enter the value of A"))
        B=eval(input("Enter the value of B"))
        res=np.linalg.solve(A,B)
        print(res)
        
    elif(choice==9):
         matrix=int(input("Choose between matrix for determinant:\n 1-> matrix1\n 2->matrix2\n "))
         if matrix==1:
            matrix=M1
         else:
            matrix=M2                #default M2 is selected
         res=np.linalg.det(matrix)
         print(res)
    elif(choice==10):
        matrix=int(input("Choose between matrix for Inverse:\n 1-> matrix1\n 2->matrix2\n "))
        if matrix==1:
            matrix=M1
        else:
            matrix=M2                #default M2 is selected
        res=np.linalg.inv(matrix)
        print(res)
    elif(choice==11):
        matrix=int(input("Choose between matrix for Inverse:\n 1-> matrix1\n 2->matrix2\n "))
        if matrix==1:
            matrix=M1
        else:
            matrix=M2                #default M2 is selected
        eigenvalues, eigenvectors = np.linalg.eig(matrix)
        print(f"eigenvalues:{eigenvalues}\n eigenvectors:{eigenvectors}")
    elif(choice==12):
        M1,M2=setmatrix()
        print("Matrix set successfully")
    elif(choice==13):
        print("Ending Program...")
        time.sleep(5)
        print("Program Ended")
        break
    else:
        print("Enter a valid choice\n")
    
    
    
    
    

Waiting for  Matrix Initialization...
